"""
detector.py — Person 2 (Model Engineer)

Loads the OWL-ViT model and runs inference on the dataset generated by Person 1.
Outputs a new CSV containing the predicted bounding boxes and confidence scores.

Usage:
  python models/detector.py --mode mockup   # Test locally on 10 rows
  python models/detector.py --mode full     # Run on Colab on 5,000 rows
"""

import os
import sys
import argparse
import torch
import pandas as pd
from PIL import Image
from tqdm import tqdm

# Add parent directory to path to allow importing config
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config

# Import HuggingFace Transformers
from transformers import OwlViTProcessor, OwlViTForObjectDetection


class OWLViTDetector:
    def __init__(self, model_name="google/owlvit-base-patch32"):
        """Initialize the OWL-ViT model and processor."""
        print(f"Loading OWL-ViT model: {model_name}...")
        
        # Select device: CUDA if available (Colab GPU), otherwise CPU (Local testing)
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        print(f"Using device: {self.device}")
        
        self.processor = OwlViTProcessor.from_pretrained(model_name)
        self.model = OwlViTForObjectDetection.from_pretrained(model_name).to(self.device)
        self.model.eval() # Set to evaluation mode
        print("Model loaded successfully!")

    def detect(self, image_path, prompt):
        """
        Run detection on a single image with a specific text prompt.
        Returns the highest confidence score and its bounding box.
        """
        try:
            # Load image
            image = Image.open(image_path).convert("RGB")
            
            # Format prompt for OWL-ViT (it expects a list of text queries)
            texts = [[prompt]] 
            
            # Preprocess image and text
            inputs = self.processor(text=texts, images=image, return_tensors="pt").to(self.device)
            
            # Run inference
            with torch.no_grad():
                outputs = self.model(**inputs)
                
            # Get target image sizes to convert bounding boxes back to original image scale
            target_sizes = torch.tensor([image.size[::-1]]).to(self.device)
            
            # Post-process outputs
            results = self.processor.post_process_object_detection(
                outputs=outputs, target_sizes=target_sizes, threshold=0.0
            )[0] # get results for the first (and only) image in batch
            
            # If no objects found
            if len(results["scores"]) == 0:
                return 0.0, None
                
            # Find the prediction with the highest confidence score
            best_idx = torch.argmax(results["scores"]).item()
            best_score = results["scores"][best_idx].item()
            best_box = results["boxes"][best_idx].tolist() # [xmin, ymin, xmax, ymax]
            
            return best_score, best_box
            
        except Exception as e:
            print(f"Error processing {image_path}: {e}")
            return 0.0, None


def process_dataset(base_dir, mode="mockup"):
    """
    Read the dataset, run OWL-ViT on each row, and save the results.
    """
    # 1. Determine input and output paths
    if mode == "mockup":
        input_csv = base_dir / 'mockup_dataset.csv'
        output_csv = base_dir / 'mockup_detection_results.csv'
    else:
        input_csv = base_dir / 'hard_negative_dataset.csv'
        output_csv = base_dir / 'full_detection_results.csv'
        
    if not input_csv.exists():
        print(f"ERROR: Input dataset not found at {input_csv}")
        print("Please run Person 1's build_dataset.py first!")
        return
        
    print(f"Loading dataset from: {input_csv}")
    df = pd.read_csv(input_csv)
    print(f"Found {len(df)} rows to process.")
    
    # 2. Initialize Model
    detector = OWLViTDetector()
    
    # 3. Process each row
    pred_scores = []
    pred_boxes = []
    
    print(f"Running detection ({mode} mode)...")
    for idx, row in tqdm(df.iterrows(), total=len(df)):
        img_path = base_dir / row['image_path']
        prompt = row['prompt']
        
        # Run detection
        score, box = detector.detect(img_path, prompt)
        
        pred_scores.append(score)
        pred_boxes.append(box)
        
    # 4. Save results
    df['pred_score'] = pred_scores
    df['pred_box'] = pred_boxes
    
    df.to_csv(output_csv, index=False)
    print(f"\nDetection complete!")
    print(f"Results saved to: {output_csv}")
    print("\nPreview of results:")
    print(df[['image_id', 'prompt', 'true_label', 'pred_score']].head())


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run OWL-ViT Object Detection.")
    parser.add_argument('--data_dir', type=str, default=None, help="Override data directory")
    parser.add_argument('--mode', type=str, default='mockup', choices=['mockup', 'full'],
                        help="'mockup' for local testing, 'full' for Colab GPU execution")
    args = parser.parse_args()
    
    base_dir = config.get_base_dir(args.data_dir)
    process_dataset(base_dir, mode=args.mode)
